### PR TITLE
Fix Unresponsive Header for Mobile View

### PR DESCRIPTION
**Pull request by Fanyul**
- Fix unresponsive header for mobile view due to image height

### CODE REVIEW

**Comment by stevangoldduck** [comment]
Possible duplicate with #63

**Comment by ngkong** [comment]
i tested and it doesn't work?

**Comment by ngkong** [comment]
button still break on width between 320-360px

**Comment by Fanyul** [comment]
@ngkong please refer to #76 
Sorry for the inconvenience

**Pull request closed without merging**
